<a href="https://colab.research.google.com/github/sohyunwriter/ai-tech-archive/blob/master/numpy_dot_vs_matmul.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## numpy의 dot / matmul 차이    
https://sohyunwriter.tistory.com/31  

In [1]:
import numpy as np

In [2]:
a = np.arange(2*3*4).reshape((2, 3, 4))
b = np.arange(2*3*4).reshape((2, 4, 3))

In [3]:
a

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [4]:
b

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]],

       [[12, 13, 14],
        [15, 16, 17],
        [18, 19, 20],
        [21, 22, 23]]])

#### dot 함수

In [5]:
np.dot(a, b)

array([[[[  42,   48,   54],
         [ 114,  120,  126]],

        [[ 114,  136,  158],
         [ 378,  400,  422]],

        [[ 186,  224,  262],
         [ 642,  680,  718]]],


       [[[ 258,  312,  366],
         [ 906,  960, 1014]],

        [[ 330,  400,  470],
         [1170, 1240, 1310]],

        [[ 402,  488,  574],
         [1434, 1520, 1606]]]])

In [6]:
np.dot(a, b).shape

(2, 3, 2, 3)

#### matmul 함수

In [7]:
np.matmul(a, b)

array([[[  42,   48,   54],
        [ 114,  136,  158],
        [ 186,  224,  262]],

       [[ 906,  960, 1014],
        [1170, 1240, 1310],
        [1434, 1520, 1606]]])

In [8]:
np.matmul(a, b).shape

(2, 3, 3)

#### when error occurs

In [9]:
a = np.arange(2*3*4).reshape((3, 2, 4)) # 2*4 3박스
b = np.arange(2*3*4).reshape((2, 4, 3)) # 4*3 2박스
np.matmul(a,b)

ValueError: ignored

In [12]:
a = np.arange(2*3*4).reshape((1, 6, 4))  # 1일 때는 괜찮음
b = np.arange(2*3*4).reshape((2, 4, 3))
np.matmul(a,b)

array([[[  42,   48,   54],
        [ 114,  136,  158],
        [ 186,  224,  262],
        [ 258,  312,  366],
        [ 330,  400,  470],
        [ 402,  488,  574]],

       [[ 114,  120,  126],
        [ 378,  400,  422],
        [ 642,  680,  718],
        [ 906,  960, 1014],
        [1170, 1240, 1310],
        [1434, 1520, 1606]]])

In [11]:
a = np.arange(2*3*4).reshape((3, 4, 2)) 
b = np.arange(2*3*4).reshape((2, 4, 3)) # shape의 2번째 수가 2가 아니어서 오류
np.dot(a,b)

ValueError: ignored